server:
  name: "api-serve"
  port: 8000
  readTimeout: 60
  writeTimeout: 60
  logPath: "./logs"
  UploadSavePath: "./static/uploads"
  UploadServerUrl: "http://127.0.0.1:8000/static"
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png


mysql:
  name: "root"
  port: 3306
  host: "127.0.0.1"
  password: "123"
  dbName: "bro"


redis:
  host: "127.0.0.1"
  port: 6379
  password:

jwt:
  key: "ZVkTfRWCC5jHJli7WN41JExJ1FfsBbmW"




